import { JobResult } from "@/lib/types";

const now = new Date();
const daysAgo = (days: number) =>
  new Date(now.getTime() - days * 24 * 3600 * 1000).toISOString();

export const DEMO_JOBS: JobResult[] = [
  {
    id: "job-fullstack-1",
    title: "Full Stack Developer",
    company: "Northstar Labs",
    location: "Remote - US",
    remoteType: "remote",
    seniority: "mid",
    employmentType: "full-time",
    industry: "SaaS",
    description:
      "Build end-to-end product features using Next.js, Node.js, and PostgreSQL. Collaborate with design and product teams. Own CI/CD pipelines and observability.",
    requiredSkills: ["TypeScript", "React", "Node.js", "PostgreSQL", "Testing"],
    preferredSkills: ["Prisma", "Tailwind", "AWS", "CI/CD"],
    applyUrl: "https://example.com/greenhouse/full-stack",
    source: "Greenhouse demo",
    postedAt: daysAgo(2),
  },
  {
    id: "job-frontend-1",
    title: "Frontend Engineer",
    company: "Pixel River",
    location: "Berlin, Germany",
    remoteType: "hybrid",
    seniority: "mid",
    employmentType: "full-time",
    industry: "E-commerce",
    description:
      "Develop performant React interfaces, improve accessibility, and collaborate on design systems. Work with product analytics and experimentation.",
    requiredSkills: ["JavaScript", "React", "Tailwind", "Testing"],
    preferredSkills: ["TypeScript", "Next.js", "Figma"],
    applyUrl: "https://example.com/lever/frontend",
    source: "Lever demo",
    postedAt: daysAgo(4),
  },
  {
    id: "job-backend-1",
    title: "Backend Engineer",
    company: "LedgerForge",
    location: "London, UK",
    remoteType: "on-site",
    seniority: "senior",
    employmentType: "full-time",
    industry: "Fintech",
    description:
      "Design resilient backend services, optimize SQL queries, and improve platform reliability. Lead API architecture and security best practices.",
    requiredSkills: ["Node.js", "PostgreSQL", "Redis", "Docker", "REST"],
    preferredSkills: ["Kubernetes", "Terraform", "AWS"],
    applyUrl: "https://example.com/careers/backend",
    source: "Company Careers demo",
    postedAt: daysAgo(6),
  },
  {
    id: "job-devops-1",
    title: "DevOps Engineer",
    company: "CloudDock",
    location: "Remote - EU",
    remoteType: "remote",
    seniority: "senior",
    employmentType: "contract",
    industry: "Infrastructure",
    description:
      "Automate deployment workflows, maintain Kubernetes clusters, and enhance cloud security posture. Drive incident response and SLO governance.",
    requiredSkills: ["Docker", "Kubernetes", "AWS", "Terraform", "Linux"],
    preferredSkills: ["Python", "CI/CD", "Monitoring"],
    applyUrl: "https://example.com/search/devops",
    source: "Search Result demo",
    postedAt: daysAgo(1),
  },
  {
    id: "job-ai-1",
    title: "AI Engineer",
    company: "VectorMind",
    location: "San Francisco, USA",
    remoteType: "hybrid",
    seniority: "senior",
    employmentType: "full-time",
    industry: "AI",
    description:
      "Build LLM-powered product capabilities, manage model evaluation pipelines, and collaborate with product engineers on retrieval and inference systems.",
    requiredSkills: ["Python", "Machine Learning", "NLP", "Testing"],
    preferredSkills: ["LangChain", "TypeScript", "AWS"],
    applyUrl: "https://example.com/search/ai-engineer",
    source: "Search Result demo",
    postedAt: daysAgo(3),
  },
  {
    id: "job-product-1",
    title: "Product Engineer",
    company: "OrbitWorks",
    location: "Amsterdam, NL",
    remoteType: "hybrid",
    seniority: "mid",
    employmentType: "full-time",
    industry: "Productivity",
    description:
      "Ship user-facing features quickly, instrument usage analytics, and iterate with product managers. Balance velocity with maintainable architecture.",
    requiredSkills: ["TypeScript", "React", "Node.js", "Product Thinking"],
    preferredSkills: ["Next.js", "PostgreSQL", "A/B Testing"],
    applyUrl: "https://example.com/manual/product-engineer",
    source: "Manual Entry demo",
    postedAt: daysAgo(5),
  },
];
